spring:
  config:
    import: classpath:dev/application-db.yml,classpath:dev/application-mp.yml,classpath:dev/application-redis.yml,classpath:dev/application-satoken.yml,classpath:dev/application-jobs.yml,classpath:dev/application-file.yml