file:
  server:
    common:
      activeTypeName: MinIo
    minio:
      enabled: true
      endpoint: http://127.0.0.1:50008
      accessKey: admin
      secretKey: 111111
    local:
      rootPath: D:\code\20231001-20231101
    huawei:
      endabled: false
      endpoint:
      accessKey:
      secretKey:
    fastdfs:
      enabled: false

