sms:
  config:
    aliyun:
      ### 阿里云的apiKey
      appKey: LTAI5t8A1zJF5HwSUThj62CS
      ### 阿里云apiSecret
      appSecret: 111111
      ### 签名
      signName: 一源源码
      ### 模板code
      templateCode: SMS_463196083
email:
  config:
    define:
      emailAccount: yiyuancode@sina.com
      emailPassword: 111111
      emailSmtphost: smtp.sina.com
      ###选用手机号还是邮箱验证码验证 email 或者phone
      active: email
