spring:
  config:
    import: classpath:prod/application-db.yml,classpath:prod/application-mp.yml,classpath:prod/application-redis.yml,classpath:prod/application-satoken.yml,classpath:prod/application-jobs.yml,classpath:prod/application-file.yml,classpath:dev/application-sms.yml,classpath:prod/application-miniapp.yml

logstash:
  host: 116.63.167.31
logging:
  level:
    root: info
tlog:
  enable-invoke-time-print: true