spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:23306/admin_prod?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
