file:
  server:
    common:
      activeTypeName: MinIo
    minio:
      enabled: true
      endpoint: http://127.0.0.1:40036
      accessKey: admin
      secretKey: 111111
    local:
      rootPath: D:/files/yiyuan
    huawei:
      endabled: false
      endpoint:
      accessKey:
      secretKey:
    fastdfs:
      enabled: false

