spring:
  datasource:
    url: jdbc:mysql://43.154.183.115:40020/admin_dev?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL