file:
  server:
    common:
      activeTypeName: MinIo
    minio:
      enabled: true
      endpoint: http://116.63.167.31:1140

      accessKey: admin
      secretKey: 123/456/789
    local:
      rootPath: D:/files/yiyuan
    huawei:
      endabled: false
      endpoint:
      accessKey:
      secretKey:
    fastdfs:
      enabled: false

